# -*- coding: utf-8 -*-
"""Sia Level2_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YoFDcwmIcEPFy-iZXCp4jLl8TBM7uO4G

###필요 모듈 설치
"""

#!pip uninstall -y segmentation-models-pytorch
!pip install pretrainedmodels==0.7.4
!pip install efficientnet_pytorch==0.6.3
!pip install timm==0.4.12
!pip install -U git+https://github.com/albu/albumentations --no-cache-dir

from google.colab import drive
drive.mount('/gdrive')

import os
import numpy as np
import cv2

workspace_path = '/gdrive/My Drive/AIproject/data/LV2_dataset'
segmentation_path = '/gdrive/My Drive/AIproject/data/segmentation_models'

import sys
sys.path.append(segmentation_path)  # segmentation 소스코드 경로 설정

import glob
import json
from PIL import Image
import matplotlib.pyplot as plt
from skimage.io import imread

import torch
import numpy as np
import segmentation_models_pytorch as smp

train_path = os.path.join(workspace_path, 'training_set')
img_train_dir = os.path.join(train_path, 'images')
blabel_train_dir = os.path.join(train_path, 'labels/building')
rlabel_train_dir = os.path.join(train_path, 'labels/road')

valid_path = os.path.join(workspace_path, 'validation_set')
img_valid_dir = os.path.join(valid_path, 'images')
blabel_valid_dir = os.path.join(valid_path, 'labels/building')
rlabel_valid_dir = os.path.join(valid_path, 'labels/road')

blabel_train_list = os.listdir(blabel_train_dir)
rlabel_train_list = os.listdir(rlabel_train_dir)

blabel_valid_list = os.listdir(blabel_valid_dir)
rlabel_valid_list = os.listdir(rlabel_valid_dir)

build_road_train = list(set(blabel_train_list).intersection(rlabel_train_list))

build_road_valid = list(set(blabel_valid_list).intersection(rlabel_valid_list))

new_train_label = '/gdrive/My Drive/AIproject/data/LV2_dataset/training_set/labels/both/'
new_valid_label = '/gdrive/My Drive/AIproject/data/LV2_dataset/validation_set/labels/both/'

from torch.utils.data import DataLoader
from torch.utils.data import Dataset as BaseDataset

class Dataset(BaseDataset):
    """CamVid Dataset. Read images, apply augmentation and preprocessing transformations.
    
    Args:
        images_dir (str): path to images folder
        masks_dir (str): path to segmentation masks folder
        class_values (list): values of classes to extract from segmentation mask
        augmentation (albumentations.Compose): data transfromation pipeline 
            (e.g. flip, scale, etc.)
        preprocessing (albumentations.Compose): data preprocessing 
            (e.g. noralization, shape manipulation, etc.)
    
    """
    
    CLASSES = ['building', 'road']
    
    def __init__(
            self, 
            images_dir, 
            masks_dir, 
            classes=None, 
            augmentation=None, 
            preprocessing=None,
    ):
        self.ids = os.listdir(images_dir)
        self.images_fps = [os.path.join(images_dir, image_id) for image_id in self.ids]
        self.masks_fps = [os.path.join(masks_dir, image_id) for image_id in self.ids]
        
        # convert str names to class values on masks
        self.class_values = [self.CLASSES.index(cls.lower()) for cls in classes]

        for i in range(len(self.masks_fps)):
          self.mask_ids = np.unique(cv2.imread(self.masks_fps[i], 0))[1:]
          if len(self.mask_ids) == len(self.class_values):
            break
        
        self.augmentation = augmentation
        self.preprocessing = preprocessing
    
    def __getitem__(self, i):
        
        # read data
        image = cv2.imread(self.images_fps[i])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        mask = cv2.imread(self.masks_fps[i], 0)
        
        # extract certain classes from mask (e.g. cars)
        masks = [(mask == self.mask_ids[v]) for v in self.class_values]
        mask = np.stack(masks, axis=-1).astype('float')
        
        # apply augmentations
        if self.augmentation:
            sample = self.augmentation(image=image, mask=mask)
            image, mask = sample['image'], sample['mask']
        
        # apply preprocessing
        if self.preprocessing:
            sample = self.preprocessing(image=image, mask=mask)
            image, mask = sample['image'], sample['mask']
            
        return image, mask
        
    def __len__(self):
        return len(self.ids)

import albumentations as albu

def get_training_augmentation():
    train_transform = [

        albu.HorizontalFlip(p=0.5),

        albu.ShiftScaleRotate(scale_limit=0.5, rotate_limit=0, shift_limit=0.1, p=1, border_mode=0),

        albu.PadIfNeeded(min_height=320, min_width=320, always_apply=True, border_mode=0),
        albu.RandomCrop(height=320, width=320, always_apply=True),

        albu.IAAAdditiveGaussianNoise(p=0.5),
        albu.IAAPerspective(p=0.5),

        albu.OneOf(
            [
                albu.CLAHE(p=1),
                albu.RandomBrightness(p=1),
                albu.RandomGamma(p=1),
            ],
            p=0.9,
        ),

        albu.OneOf(
            [
                albu.IAASharpen(p=1),
                albu.Blur(blur_limit=3, p=1),
                albu.MotionBlur(blur_limit=3, p=1),
            ],
            p=0.9,
        ),

        albu.OneOf(
            [
                albu.RandomContrast(p=1),
                albu.HueSaturationValue(p=1),
            ],
            p=0.9,
        ),
    ]
    return albu.Compose(train_transform)


def get_validation_augmentation():
    """Add paddings to make image shape divisible by 32"""
    test_transform = [
        albu.PadIfNeeded(384, 480)
    ]
    return albu.Compose(test_transform)


def to_tensor(x, **kwargs):
    return x.transpose(2, 0, 1).astype('float32')


def get_preprocessing(preprocessing_fn):
    """Construct preprocessing transform
    
    Args:
        preprocessing_fn (callbale): data normalization function 
            (can be specific for each pretrained neural network)
    Return:
        transform: albumentations.Compose
    
    """
    
    _transform = [
        albu.Lambda(image=preprocessing_fn),
        albu.Lambda(image=to_tensor, mask=to_tensor),
    ]
    return albu.Compose(_transform)

"""###저장된 train_model.pth"""

save_dir = os.path.join(workspace_path, 'ckpt')

bst_model = torch.load(os.path.join(save_dir, 'train_model.pth'))
bst_model.eval()

ENCODER = 'se_resnext50_32x4d'
ENCODER_WEIGHTS = 'imagenet'
CLASSES = ['building','road']
ACTIVATION = 'sigmoid' # could be None for logits or 'softmax2d' for multiclass segmentation
DEVICE = 'cuda'

preprocessing_fn = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)

valid_dataset = Dataset(img_valid_dir, 
                        new_valid_label,
                        augmentation=get_validation_augmentation(), 
                        preprocessing=get_preprocessing(preprocessing_fn),     
                        classes = CLASSES,
                        )

valid_loader = torch.utils.data.DataLoader(
    valid_dataset,
    batch_size = 8,
    shuffle = False,
    num_workers = 1
)

loss = smp.utils.losses.DiceLoss()
metrics = [
    smp.utils.metrics.IoU(threshold=0.25),
]

valid_epoch = smp.utils.train.ValidEpoch(
    bst_model, 
    loss=loss, 
    metrics=metrics, 
    device=DEVICE,
    verbose=True,
)

"""###모델 훈련"""

import time
max_score = 0

prevTime = time.time()
  
valid_logs = valid_epoch.run(valid_loader)
curTime = time.time()

sec = curTime - prevTime
fps = sec / 18
print('FPS : ', fps)

if max_score < valid_logs['iou_score']:
  max_score = valid_logs['iou_score']
  print('Model saved')

print('max_score =' + str(max_score))

"""###이미지 시각화"""

valid_dataset_vis = Dataset(
    img_valid_dir, 
    new_valid_label, 
    classes=['building','road'],
)

def mask_color(mask):
  output = np.zeros(mask[0].shape, np.uint8)

  for i, value in enumerate(mask):
    output[value == 1] = i+1
  return output

# helper function for data visualization
def visualize(**images):
    """PLot images in one row."""
    n = len(images)
    plt.figure(figsize=(16, 5))
    for i, (name, image) in enumerate(images.items()):
        plt.subplot(1, n, i + 1)
        plt.xticks([])
        plt.yticks([])
        plt.title(' '.join(name.split('_')).title())
        plt.imshow(image)
    plt.show()

for i in range(5):
    n = np.random.choice(len(valid_dataset))
    
    image_vis = valid_dataset_vis[n][0].astype('uint8')
    image, gt_mask = valid_dataset[n]
    
    
    gt_mask = gt_mask.squeeze()
    
    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = bst_model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
    visualize(
        image=image_vis,
        both_gt = mask_color(gt_mask),
        both_pr = mask_color(pr_mask),
    )